### PR TITLE
165 Fixes the build breakage on the master branch

### LINKED ISSUE #165: Build broken after merging conflicting PRs #144 and #150
**Description**
The `master` branch is currently broken and fails to compile due to conflicts between two merged pull requests.

**Build Errors**
The `make` command fails with multiple TypeScript compilation errors related to ANTLR4 imports and API usage:

<details>
<summary>🛠️ Build Log (17 errors)</summary>

```bash
make
java -jar antlr4/antlr4-4.13.2-complete.jar -o src/parser -visitor -Dlanguage=TypeScript Eo.g4 
npx tsc -b
src/eoAst.ts:4:27 - error TS2307: Cannot find module 'antlr4ts/tree/ParseTree' or its corresponding type declarations.

4 import { ParseTree } from "antlr4ts/tree/ParseTree";
                            ~~~~~~~~~~~~~~~~~~~~~~~~~

src/eoAst.ts:13:26 - error TS2307: Cannot find module 'antlr4ts/tree/RuleNode' or its corresponding type declarations.

13 import { RuleNode } from "antlr4ts/tree/RuleNode";
                            ~~~~~~~~~~~~~~~~~~~~~~~~

src/eoAst.ts:84:23 - error TS2339: Property 'text' does not exist on type 'ObjectContext'.

84             text: ctx.text,
                         ~~~~

src/eoAst.ts:109:23 - error TS2339: Property 'text' does not exist on type 'BoundContext'.

109             text: ctx.text
                          ~~~~

src/eoAst.ts:133:23 - error TS2339: Property 'text' does not exist on type 'MasterBodyContext'.

133             text: ctx.text
                          ~~~~

src/eoAst.ts:152:33 - error TS2551: Property 'childCount' does not exist on type 'ObjectContext'. Did you mean 'getChildCount'?

152         for (let i = 0; i < ctx.childCount; i++) {
                                    ~~~~~~~~~~

  node_modules/antlr4/src/antlr4/context/ParserRuleContext.d.ts:17:5
    17     getChildCount() : number;
           ~~~~~~~~~~~~~
    'getChildCount' is declared here.

src/eoAst.ts:198:39 - error TS2551: Property 'childCount' does not exist on type 'SubMasterContext'. Did you mean 'getChildCount'?

198         for (let i = 0; i < subMaster.childCount; i++) {
                                          ~~~~~~~~~~

  node_modules/antlr4/src/antlr4/context/ParserRuleContext.d.ts:17:5
    17     getChildCount() : number;
           ~~~~~~~~~~~~~
    'getChildCount' is declared here.

src/eoAst.ts:240:26 - error TS2339: Property 'text' does not exist on type 'ObjectContext'.

240         const text = ctx.text;
                             ~~~~

src/eoAst.ts:255:26 - error TS2339: Property 'text' does not exist on type 'BoundContext'.

255         const text = ctx.text;
                             ~~~~

src/eoAst.ts:273:26 - error TS2339: Property 'text' does not exist on type 'MasterBodyContext'.

273         const text = ctx.text;
                             ~~~~

src/eoAst.ts:291:19 - error TS2339: Property 'charPositionInLine' does not exist on type 'Token'.

291             start.charPositionInLine,
                      ~~~~~~~~~~~~~~~~~~

src/eoAst.ts:293:18 - error TS2339: Property 'charPositionInLine' does not exist on type 'Token'.

293             stop.charPositionInLine + (stop.text?.length || 0)
                     ~~~~~~~~~~~~~~~~~~

src/eoDocumentSymbol.ts:5:27 - error TS2307: Cannot find module 'antlr4ts/tree/ErrorNode' or its corresponding type declarations.

5 import { ErrorNode } from "antlr4ts/tree/ErrorNode";
                            ~~~~~~~~~~~~~~~~~~~~~~~~~

src/eoDocumentSymbol.ts:6:27 - error TS2307: Cannot find module 'antlr4ts/tree/ParseTree' or its corresponding type declarations.

6 import { ParseTree } from "antlr4ts/tree/ParseTree";
                            ~~~~~~~~~~~~~~~~~~~~~~~~~

src/eoDocumentSymbol.ts:7:26 - error TS2307: Cannot find module 'antlr4ts/tree/RuleNode' or its corresponding type declarations.

7 import { RuleNode } from "antlr4ts/tree/RuleNode";
                           ~~~~~~~~~~~~~~~~~~~~~~~~

src/eoDocumentSymbol.ts:8:30 - error TS2307: Cannot find module 'antlr4ts/tree/TerminalNode' or its corresponding type declarations.

8 import { TerminalNode } from "antlr4ts/tree/TerminalNode";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/eoDocumentSymbol.ts:14:10 - error TS2614: Module '"./parser/EoVisitor"' has no exported member 'EoVisitor'. Did you mean to use 'import EoVisitor from "./parser/EoVisitor"' instead?

14 import { EoVisitor } from "./parser/EoVisitor";
            ~~~~~~~~~


Found 17 errors.

make: *** [Makefile:34: tsc-compiled] Ошибка 1
```
</details>

**Root Cause**
The conflict arises from merging two incompatible changes:
1. **PR #144** (`Thayorns/92`) - uses the legacy `antlr4ts` library
2. **PR #150** (`svmukhin/147`) - migrates to the official ANTLR4 TypeScript target

These changes introduced conflicting dependencies and APIs, particularly affecting the `textDocument/documentSymbol` functionality.

**Proposed Solution**
Update the functionality added in PR #144 (`textDocument/documentSymbol`) to use the official ANTLR4 TypeScript target API instead of `antlr4ts`.

**Additional Context**
The specific issues include:
- Missing modules from `antlr4ts/tree/`
- Incorrect property access (`ctx.text` vs `ctx.getText()`)
- Missing method calls (`getChildCount()` vs `childCount`)
- Import/export syntax conflicts

### PR DESCRIPTION
**Pull request by svmukhin**
Closes #165 

### 🎯 Purpose
Fixes the build breakage on the master branch caused by a merge conflict between PR #144 (textDocument/documentSymbol implementation) and PR #150 (ANTLR4 migration).

### 🐛 Problem
The master branch failed to compile with 17 TypeScript errors due to incompatible changes:
- **PR #144** introduced `textDocument/documentSymbol` functionality using the legacy `antlr4ts` library
- **PR #150** migrated the entire codebase to the official ANTLR4 TypeScript target
- The merge resulted in `eoAst.ts` and `eoDocumentSymbol.ts` using outdated `antlr4ts` APIs that no longer exist

### ✅ Solution
Updated the document symbol functionality to use the official ANTLR4 TypeScript target API:

### CODE REVIEW

**Comment by 0crat** [comment]
@svmukhin Great work on your contribution! 🎉 You've earned **+16 points** and your total score is now **+86**. [Keep the momentum going](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) with quality contributions! Check your progress on the [leaderboard](https://www.eolang.org/zerocracy/objectionary-vitals.html) and don't forget to review your [Zerocracy account](https://www.zerocracy.com/) for updates.
